# Generated by Django 5.1.7 on 2025-03-18 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('battycoda_app', '0002_taskbatch_task'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='is_done',
            field=models.BooleanField(default=False, help_text='Indicates that the task has been fully reviewed and labeled'),
        ),
        migrations.AddField(
            model_name='task',
            name='label',
            field=models.CharField(blank=True, help_text='Final expert label assigned to this task', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='task',
            name='notes',
            field=models.TextField(blank=True, help_text='Additional notes or observations about this task', null=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('done', 'Done')], default='pending', max_length=20),
        ),
    ]
