# Generated by Django 5.1.7 on 2025-03-18 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('battycoda_app', '0003_task_is_done_task_label_task_notes_alter_task_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskbatch',
            name='wav_file',
            field=models.FileField(blank=True, null=True, upload_to='task_batches/'),
        ),
    ]
