# Generated by Django 5.1.7 on 2025-03-18 15:03

from django.db import migrations


def remove_taskbatches(apps, schema_editor):
    # Get models
    TaskBatch = apps.get_model('battycoda_app', 'TaskBatch')
    Task = apps.get_model('battycoda_app', 'Task')
    
    # Delete all existing tasks linked to TaskBatches
    Task.objects.filter(batch__isnull=False).delete()
    
    # Delete all TaskBatches
    TaskBatch.objects.all().delete()


def reverse_migration(apps, schema_editor):
    # This is a destructive migration that cannot be reversed
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('battycoda_app', '0009_create_salleslab_team'),
    ]

    operations = [
        migrations.RunPython(remove_taskbatches, reverse_migration),
    ]