# Generated by Django 5.1.7 on 2025-03-23 03:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('battycoda_app', '0017_populate_team_memberships'),
    ]

    operations = [
    ]
