# Generated by Django 5.1.7 on 2025-03-23 04:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('battycoda_app', '0018_remove_fields'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='call',
            name='description',
        ),
        migrations.RemoveField(
            model_name='species',
            name='scientific_name',
        ),
        migrations.AlterField(
            model_name='call',
            name='long_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
