# Generated by Django 5.1.7 on 2025-03-23 22:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('battycoda_app', '0019_make_long_name_optional'),
    ]

    operations = [
        migrations.CreateModel(
            name='DetectionRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('progress', models.FloatField(default=0.0, help_text='Progress percentage from 0-100')),
                ('error_message', models.TextField(blank=True, null=True)),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detection_runs', to='battycoda_app.taskbatch')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detection_runs', to='auth.user')),
                ('team', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='detection_runs', to='battycoda_app.team')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DetectionResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('detection_run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='battycoda_app.detectionrun')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detection_results', to='battycoda_app.task')),
            ],
            options={
                'ordering': ['task__onset'],
            },
        ),
        migrations.CreateModel(
            name='CallProbability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('probability', models.FloatField(help_text='Probability value between 0-1')),
                ('call', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='probabilities', to='battycoda_app.call')),
                ('detection_result', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='probabilities', to='battycoda_app.detectionresult')),
            ],
            options={
                'ordering': ['-probability'],
            },
        ),
    ]