# Generated by Django 5.1.7 on 2025-03-23 23:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("battycoda_app", "0020_add_automated_detection_models"),
    ]

    operations = [
        migrations.AddField(
            model_name="detectionrun",
            name="algorithm_type",
            field=models.CharField(
                choices=[
                    ("full_probability", "Full Probability Distribution"),
                    ("highest_only", "Highest Probability Only"),
                ],
                default="full_probability",
                help_text="Whether the algorithm returns full probability distributions or only the highest probability",
                max_length=20,
            ),
        ),
    ]
