# Generated by Django 5.1.7 on 2025-03-24 00:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("battycoda_app", "0021_detectionrun_algorithm_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="detectionrun",
            name="algorithm_type",
            field=models.CharField(
                choices=[
                    ("full_probability", "Full Probability Distribution"),
                    ("highest_only", "Highest Probability Only"),
                ],
                default="highest_only",
                help_text="Whether the algorithm returns full probability distributions or only the highest probability",
                max_length=20,
            ),
        ),
        migrations.CreateModel(
            name="Classifier",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(help_text="Name of the classification algorithm", max_length=255)),
                (
                    "description",
                    models.TextField(blank=True, help_text="Description of how the algorithm works", null=True),
                ),
                (
                    "response_format",
                    models.CharField(
                        choices=[
                            ("full_probability", "Full Probability Distribution"),
                            ("highest_only", "Highest Probability Only"),
                        ],
                        help_text="Format of the response returned by this algorithm",
                        max_length=20,
                    ),
                ),
                (
                    "celery_task",
                    models.CharField(
                        default="battycoda_app.audio.tasks.run_call_detection",
                        help_text="Fully qualified Celery task name to execute this algorithm",
                        max_length=255,
                    ),
                ),
                (
                    "service_url",
                    models.CharField(
                        blank=True, help_text="URL of the external service, if applicable", max_length=255, null=True
                    ),
                ),
                (
                    "endpoint",
                    models.CharField(blank=True, help_text="Endpoint path for the service", max_length=255, null=True),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, help_text="Whether this classifier is currently active"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "team",
                    models.ForeignKey(
                        blank=True,
                        help_text="Team that owns this classifier. If null, it's available to all teams",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="classifiers",
                        to="battycoda_app.team",
                    ),
                ),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.AddField(
            model_name="detectionrun",
            name="classifier",
            field=models.ForeignKey(
                blank=True,
                help_text="The classifier algorithm used for this detection run",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="detection_runs",
                to="battycoda_app.classifier",
            ),
        ),
    ]
