# Generated by Django 5.1.7 on 2025-03-24 00:13

from django.db import migrations
import os


def create_rdirect_classifier(apps, schema_editor):
    # Get the Classifier model
    Classifier = apps.get_model('battycoda_app', 'Classifier')
    
    # Get RDIRECT_URL from environment or use default
    rdirect_url = os.environ.get('RDIRECT_URL', 'http://localhost:8100')
    
    # Create the R-direct classifier
    Classifier.objects.create(
        name='R-direct Classifier',
        description='Default R-direct service integration for bat call detection. Returns only the most likely call type.',
        response_format='highest_only',
        celery_task='battycoda_app.audio.tasks.run_call_detection',
        service_url=rdirect_url,
        endpoint='/classify',
        is_active=True,
        team=None  # Available to all teams
    )


class Migration(migrations.Migration):
    dependencies = [
        ("battycoda_app", "0022_alter_detectionrun_algorithm_type_classifier_and_more"),
    ]

    operations = [
        migrations.RunPython(create_rdirect_classifier),
    ]
