# Generated by Django 5.1.7 on 2025-03-26 22:01

from django.db import migrations, models
import re


def clean_species_names(apps, schema_editor):
    """
    Clean up species names by removing group suffixes.
    For example, "Carollia - kevin5's Group" becomes just "Carollia".
    """
    Species = apps.get_model('battycoda_app', 'Species')
    
    # Pattern to match species with group suffix: "Name - Group"
    pattern = r'^(.+) - (.+)$'
    
    for species in Species.objects.all():
        match = re.match(pattern, species.name)
        if match:
            # Get the base name without group suffix
            base_name = match.group(1).strip()
            
            # Check if this would cause a conflict within the same group
            existing = Species.objects.filter(name=base_name, group=species.group).first()
            if existing and existing.id != species.id:
                # Append a unique identifier to avoid conflict
                species.name = f"{base_name} ({species.id})"
            else:
                species.name = base_name
            
            species.save()


class Migration(migrations.Migration):

    dependencies = [
        ('battycoda_app', '0029_fix_species_unique_constraint'),
    ]

    operations = [
        # First, run the data migration to clean up names
        migrations.RunPython(clean_species_names, migrations.RunPython.noop),
    ]