# Generated by Django 5.1.7 on 2025-03-26 22:27

import battycoda_app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('battycoda_app', '0030_clean_species_names'),
    ]

    operations = [
        migrations.AlterField(
            model_name='species',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=battycoda_app.models.get_species_image_path),
        ),
    ]
