# Generated by Django 5.1.7 on 2025-03-27 00:54

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("battycoda_app", "0032_update_project_uniqueness"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="taskbatch",
            options={"ordering": ["name"]},
        ),
        migrations.AlterUniqueTogether(
            name="taskbatch",
            unique_together={("name", "group")},
        ),
    ]
