# Generated by Django 5.1.7 on 2025-03-27 06:31

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("battycoda_app", "0035_create_missing_segmentations"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="recording",
            options={"ordering": ["-created_at"], "verbose_name": "Recording", "verbose_name_plural": "Recordings"},
        ),
        migrations.AlterUniqueTogether(
            name="recording",
            unique_together={("name", "group")},
        ),
    ]
