# Generated by Django 5.1.7 on 2025-03-27 12:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("battycoda_app", "0036_add_recording_name_uniqueness"),
    ]

    operations = [
        migrations.AddField(
            model_name="segmentation",
            name="manually_edited",
            field=models.BooleanField(
                default=False, help_text="Indicates if this segmentation was manually edited after initial creation"
            ),
        ),
    ]
