# Generated by Django 5.1.7 on 2025-03-27 14:42

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("battycoda_app", "0040_add_theme_preference"),
        ("battycoda_app", "0042_taskbatch_detection_run"),
    ]

    operations = []
