# Generated by Django 5.1.7 on 2025-03-27 21:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("battycoda_app", "0044_change_segmentation_to_many"),
    ]

    operations = [
        migrations.AddField(
            model_name="recording",
            name="sample_rate",
            field=models.IntegerField(blank=True, help_text="Sample rate of the recording in Hz", null=True),
        ),
    ]